[build-system]
requires = ["setuptools>=42", "wheel", "torch>=2.0.0", "ninja", "numpy"]
build-backend = "setuptools.build_meta" 
[project]
name = "deepseek-cpp"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "safetensors",
    "torch>=2.0.0",
    "ninja",
    "numpy"
]